name: Deploy Django App to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get Git Commit SHA
      id: get_version
      run: echo "::set-output name=sha::$(git rev-parse HEAD)"

    - name: Set environment variable
      run: echo "DOCK_TAG=${{ steps.get_version.outputs.sha }}" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build . -t 224574/django-todo:${{ env.DOCK_TAG }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push 224574/django-todo:${{ env.DOCK_TAG }}

    - name: Update deployment with new image
      run: sed -i "s|tagname|${{ env.DOCK_TAG }}|" kubernetes/django-deployment.yaml

    - name: Set up kubeconfig
      id: setup-kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}"  > $HOME/.kube/config

    - name: Ensure kubectl is installed
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl get pods
        kubectl apply -f kubernetes/postgress-pv.yaml
        kubectl apply -f kubernetes/postgres-deployment.yaml
        kubectl apply -f kubernetes/postgres-service.yaml
        kubectl apply -f kubernetes/django-deployment.yaml
        kubectl apply -f kubernetes/django-service.yaml
